// portfolio-rn/src/components/AboutSection.tsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Colors } from '../constants/colors';

const stats = [
  { number: '8+', label: 'Years Experience' },
  { number: '10+', label: 'Technologies' },
  { number: '20+', label: 'Projects Delivered' },
  { number: '4+', label: 'Team Members Led' },
];

export default function AboutSection() {
  return (
    <View style={styles.section}>
      <Text style={styles.title}>About Me</Text>
      <Text style={styles.subtitle}>
        Technical Lead with 8+ years of experience in full-stack development
      </Text>

      <View style={styles.statsGrid}>
        {stats.map(stat => (
          <View key={stat.label} style={styles.statCard}>
            <Text style={styles.statNumber}>{stat.number}</Text>
            <Text style={styles.statLabel}>{stat.label}</Text>
          </View>
        ))}
      </View>

      <View style={styles.content}>
        <Text style={styles.contentTitle}>Building Digital Excellence</Text>
        <Text style={styles.contentText}>
          As a Technical Lead at Paper.id, I orchestrate the development of innovative solutions
          while mentoring a diverse team of engineers. My journey in tech has equipped me with a
          comprehensive skill set spanning from backend architecture to frontend implementation.
        </Text>
        <Text style={styles.contentText}>
          I specialize in creating scalable web applications, implementing microservices
          architectures, and ensuring code quality across teams. My approach combines technical
          expertise with strong leadership to deliver products that make a difference.
        </Text>
        <Text style={styles.contentText}>
          I also help the product team calculate and provide solutions about what they want to
          build.
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  section: {
    paddingVertical: 48,
    paddingHorizontal: 20,
    backgroundColor: Colors.veryLightBlue,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: Colors.darkBlue,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: Colors.gray,
    textAlign: 'center',
    marginBottom: 32,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    width: '47.5%',
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    shadowColor: Colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  statNumber: {
    fontSize: 36,
    fontWeight: '800',
    color: Colors.primaryBlue,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: Colors.gray,
    textAlign: 'center',
  },
  content: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 20,
    shadowColor: Colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  contentTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.darkBlue,
    marginBottom: 12,
  },
  contentText: {
    fontSize: 14,
    color: Colors.darkGray,
    lineHeight: 22,
    marginBottom: 12,
  },
});

// src/app/components/about-section/about-section.component.ts
import { Component } from '@angular/core';
import { TerminalChromeComponent } from '../terminal-chrome/terminal-chrome.component';

const metrics = [
  { value: '$2M+', label: 'daily transactions' },
  { value: '10M+', label: 'monthly transactions' },
  { value: '40%', label: 'faster deployments' },
  { value: '35%', label: 'fewer bugs' },
];

const stats = [
  { value: '20+', label: 'projects delivered' },
  { value: '15+', label: 'engineers led' },
  { value: '99.9%', label: 'uptime goal' },
];

@Component({
  selector: 'app-about-section',
  standalone: true,
  imports: [TerminalChromeComponent],
  templateUrl: './about-section.component.html',
})
export class AboutSectionComponent {
  metrics = metrics;
  stats = stats;
}

<section id="about" class="border-t border-term-dim">
  <div class="max-w-content mx-auto px-5 sm:px-6 md:px-14 py-14 sm:py-16 md:py-[88px]">
    <div class="section-label">// the philosophy</div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-start">
      <div class="min-w-0">
        <h2 class="m-0 mb-5 sm:mb-[26px] text-[28px] sm:text-[32px] md:text-[44px] font-bold leading-[1.1] tracking-[-0.02em]">
          Precision in Code,
          <br />
          Vision in Strategy<span class="text-terminal-primary">.</span>
        </h2>
        <p class="m-0 mb-[18px] text-[15px] sm:text-[15.5px] leading-[1.7] text-terminal-muted">
          As a Technical Lead, I orchestrate development of innovative solutions while mentoring
          engineers. My approach combines backend architecture expertise with strong leadership
          to deliver products that make a difference.
        </p>
        <p class="m-0 text-[15px] sm:text-[15.5px] leading-[1.7] text-terminal-muted">
          I specialize in creating scalable web applications, implementing microservices
          architectures, and ensuring code quality across teams. I also help product teams
          calculate effort and shape solutions for what they want to build.
        </p>

        <div class="grid grid-cols-3 gap-4 sm:flex sm:flex-wrap sm:gap-8 md:gap-11 mt-8 sm:mt-[38px]">
          @for (stat of stats; track stat.label) {
            <div>
              <div class="text-[26px] sm:text-[34px] font-bold text-terminal-blue">{{ stat.value }}</div>
              <div class="font-mono text-[10px] sm:text-[11px] text-terminal-faint mt-1 leading-snug">
                {{ stat.label }}
              </div>
            </div>
          }
        </div>
      </div>

      <div class="bg-terminal-surface border border-term rounded-[10px] overflow-hidden self-start w-full min-w-0">
        <app-terminal-chrome title="current --status" size="sm" />
        <div class="px-4 sm:px-6 py-5 sm:py-[26px]">
          <div class="font-mono text-[11.5px] text-terminal-faint mb-1.5">currently at</div>
          <div class="text-[20px] sm:text-[22px] font-bold">Sobat Bisnis Group</div>
          <div class="font-mono text-[11px] sm:text-xs text-terminal-blue mt-1 mb-5 sm:mb-6">
            senior full stack developer — java · angularjs · hybrid
          </div>
          <div class="grid grid-cols-2 gap-2.5 sm:gap-3.5">
            @for (metric of metrics; track metric.label) {
              <div class="border border-term rounded-md p-3 sm:p-4 min-w-0">
                <div class="text-xl sm:text-2xl font-bold text-terminal-blue">{{ metric.value }}</div>
                <div class="font-mono text-[10px] sm:text-[10.5px] text-terminal-faint mt-1 leading-snug break-words">
                  {{ metric.label }}
                </div>
              </div>
            }
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
