// src/app/components/header/header.component.ts
import { isPlatformBrowser, NgTemplateOutlet } from '@angular/common';
import { Component, effect, HostListener, inject, PLATFORM_ID, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { filter, map, startWith } from 'rxjs';

interface NavItem {
  label: string;
  href: string;
  id: string;
}

const navItems: NavItem[] = [
  { label: './home', href: '#home', id: 'home' },
  { label: './skills', href: '#skills', id: 'skills' },
  { label: './portfolio', href: '/portfolio', id: 'portfolio' },
  { label: './experience', href: '#experience', id: 'experience' },
  { label: './blog', href: '/blog', id: 'blog' },
  { label: './contact', href: '#contact', id: 'contact' },
];

/** router.url and NavigationEnd.urlAfterRedirects can include a #fragment or ?query — strip both so path comparisons (e.g. isHome) aren't thrown off by a URL like "/#experience". */
function stripFragmentAndQuery(url: string): string {
  return url.split('#')[0].split('?')[0] || '/';
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, NgTemplateOutlet],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  private router = inject(Router);
  private isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  navItems = navItems;
  menuOpen = signal(false);
  activeId = signal('home');

  pathname = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map(e => stripFragmentAndQuery(e.urlAfterRedirects)),
      startWith(stripFragmentAndQuery(this.router.url))
    ),
    { initialValue: stripFragmentAndQuery(this.router.url) }
  );

  isHome = () => this.pathname() === '/';

  constructor() {
    effect(onCleanup => {
      if (!this.isBrowser || !this.isHome()) return;

      const sectionIds = navItems.filter(item => item.href.startsWith('#')).map(item => item.id);
      const elements = sectionIds
        .map(id => document.getElementById(id))
        .filter((el): el is HTMLElement => el !== null);

      if (elements.length === 0) return;

      const observer = new IntersectionObserver(
        entries => {
          const visible = entries
            .filter(e => e.isIntersecting)
            .sort((a, b) => b.intersectionRatio - a.intersectionRatio);

          if (visible.length > 0) {
            this.activeId.set(visible[0].target.id);
          }
        },
        {
          rootMargin: '-20% 0px -55% 0px',
          threshold: [0, 0.1, 0.25, 0.5, 0.75, 1],
        }
      );

      elements.forEach(el => observer.observe(el));
      onCleanup(() => observer.disconnect());
    });
  }

  @HostListener('window:resize')
  onResize(): void {
    if (this.isBrowser && window.innerWidth >= 1024) this.menuOpen.set(false);
  }

  handleAnchorNav(href: string, id: string): void {
    this.activeId.set(id);
    this.menuOpen.set(false);
    if (!this.isBrowser) return;
    const target = document.querySelector(href);
    if (!target) return;
    const top = target.getBoundingClientRect().top + window.scrollY - 72;
    window.scrollTo({ top, behavior: 'smooth' });
  }

  toggleMenu(): void {
    this.menuOpen.set(!this.menuOpen());
  }

  isPageLink(item: NavItem): boolean {
    return item.href.startsWith('/');
  }

  isItemActive(item: NavItem): boolean {
    if (this.isPageLink(item)) {
      return this.pathname() === item.href || this.pathname().startsWith(`${item.href}/`);
    }
    return this.isHome() && this.activeId() === item.id;
  }

  navClass(item: NavItem, base = ''): string {
    const state = this.isItemActive(item)
      ? 'text-terminal-text'
      : 'text-terminal-dim hover:text-terminal-text';
    return `${base} transition-colors ${state}`;
  }

  offHomeAnchorHref(item: NavItem): string {
    return `/${item.href}`;
  }
}

<ng-template #navItemTpl let-item let-base="base">
  @if (isPageLink(item)) {
    <a
      [routerLink]="item.href"
      (click)="menuOpen.set(false)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'page' : null"
      >{{ item.label }}</a
    >
  } @else if (!isHome()) {
    <a
      [href]="offHomeAnchorHref(item)"
      (click)="menuOpen.set(false)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'page' : null"
      >{{ item.label }}</a
    >
  } @else {
    <button
      (click)="handleAnchorNav(item.href, item.id)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'true' : null"
    >
      {{ item.label }}
    </button>
  }
</ng-template>

<header class="sticky top-0 z-50 border-b border-term-dim bg-[rgba(6,11,22,0.85)] backdrop-blur-md font-mono text-[13px]">
  <div class="flex justify-between items-center gap-4 px-5 sm:px-6 md:px-14 py-[18px] max-w-content mx-auto">
    @if (isHome()) {
      <button
        (click)="handleAnchorNav('#home', 'home')"
        class="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
      >
        ~/yuko-pangestu
      </button>
    } @else {
      <a
        routerLink="/"
        class="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
      >
        ~/yuko-pangestu
      </a>
    }

    <!-- Desktop nav — lg+ so tablet doesn't crush 6 links + CTA -->
    <nav class="hidden lg:flex items-center gap-6 xl:gap-[30px]" aria-label="Primary">
      @for (item of navItems; track item.href) {
        <ng-container [ngTemplateOutlet]="navItemTpl" [ngTemplateOutletContext]="{ $implicit: item, base: '' }" />
      }
    </nav>

    <div class="flex items-center gap-3 sm:gap-4 shrink-0">
      <a
        href="mailto:yuko.pangestu@gmail.com"
        class="hidden lg:inline-block border border-terminal-primary text-terminal-blue px-[18px] py-2 rounded hover:bg-terminal-primary hover:text-white transition-colors"
      >
        hire --me
      </a>
      <button
        class="lg:hidden text-terminal-dim p-1 hover:text-terminal-text"
        (click)="toggleMenu()"
        aria-label="Toggle menu"
        [attr.aria-expanded]="menuOpen()"
      >
        <span class="font-mono text-sm">{{ menuOpen() ? 'close' : 'menu' }}</span>
      </button>
    </div>
  </div>

  @if (menuOpen()) {
    <div id="mobile-menu" class="lg:hidden flex flex-col px-5 sm:px-6 pb-6 gap-1 border-t border-term-dim">
      @for (item of navItems; track item.href) {
        <ng-container
          [ngTemplateOutlet]="navItemTpl"
          [ngTemplateOutletContext]="{ $implicit: item, base: 'text-left py-3 border-b border-term-dim last:border-0' }"
        />
      }
      <a
        href="mailto:yuko.pangestu@gmail.com"
        class="border border-terminal-primary text-terminal-blue px-[18px] py-3 rounded text-center mt-3 hover:bg-terminal-primary hover:text-white transition-colors"
      >
        hire --me
      </a>
    </div>
  }
</header>

// portfolio-web/src/components/Header.tsx
'use client';

import { useState, useEffect } from 'react';
import { FaBars, FaTimes } from 'react-icons/fa';

const navItems = [
  { label: 'Home', href: '#home' },
  { label: 'Skills', href: '#skills' },
  { label: 'About', href: '#about' },
  { label: 'Portfolio', href: '#portfolio' },
  { label: 'Experience', href: '#experience' },
  { label: 'Contact', href: '#contact' },
];

export default function Header() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const handleNav = (href: string) => {
    setMenuOpen(false);
    const target = document.querySelector(href);
    if (!target) return;
    const top = target.getBoundingClientRect().top + window.scrollY - 64;
    window.scrollTo({ top, behavior: 'smooth' });
  };

  return (
    <header
      className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${
        scrolled ? 'bg-blue-900 shadow-lg shadow-blue-900/30' : 'bg-blue-900/95 backdrop-blur-sm'
      }`}
    >
      <div className="max-w-6xl mx-auto px-5 flex items-center justify-between h-16">
        <button
          onClick={() => handleNav('#home')}
          className="text-white font-extrabold text-xl tracking-widest hover:text-blue-300 transition-colors"
        >
          YP
        </button>

        {/* Desktop nav */}
        <nav className="hidden md:flex items-center gap-7">
          {navItems.map(item => (
            <button
              key={item.href}
              onClick={() => handleNav(item.href)}
              className="text-white/75 hover:text-white text-base font-medium transition-colors"
            >
              {item.label}
            </button>
          ))}
        </nav>

        {/* Mobile toggle */}
        <button
          className="md:hidden text-white p-1"
          onClick={() => setMenuOpen(o => !o)}
          aria-label="Toggle menu"
        >
          {menuOpen ? <FaTimes size={20} /> : <FaBars size={20} />}
        </button>
      </div>

      {/* Mobile menu */}
      {menuOpen && (
        <div className="md:hidden bg-blue-900 border-t border-white/10 px-5 pb-4">
          {navItems.map(item => (
            <button
              key={item.href}
              onClick={() => handleNav(item.href)}
              className="block w-full text-left text-white/75 hover:text-white py-3.5 text-base font-medium border-b border-white/5 last:border-0 transition-colors"
            >
              {item.label}
            </button>
          ))}
        </div>
      )}
    </header>
  );
}
