// src/app/components/header/header.component.ts
import { isPlatformBrowser, NgTemplateOutlet } from '@angular/common';
import { Component, effect, HostListener, inject, PLATFORM_ID, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { filter, map, startWith } from 'rxjs';

interface NavItem {
  label: string;
  href: string;
  id: string;
}

const navItems: NavItem[] = [
  { label: './home', href: '#home', id: 'home' },
  { label: './skills', href: '#skills', id: 'skills' },
  { label: './portfolio', href: '/portfolio', id: 'portfolio' },
  { label: './experience', href: '#experience', id: 'experience' },
  { label: './blog', href: '/blog', id: 'blog' },
  { label: './contact', href: '#contact', id: 'contact' },
];

/** router.url and NavigationEnd.urlAfterRedirects can include a #fragment or ?query — strip both so path comparisons (e.g. isHome) aren't thrown off by a URL like "/#experience". */
function stripFragmentAndQuery(url: string): string {
  return url.split('#')[0].split('?')[0] || '/';
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, NgTemplateOutlet],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  private router = inject(Router);
  private isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  navItems = navItems;
  menuOpen = signal(false);
  activeId = signal('home');

  pathname = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map(e => stripFragmentAndQuery(e.urlAfterRedirects)),
      startWith(stripFragmentAndQuery(this.router.url))
    ),
    { initialValue: stripFragmentAndQuery(this.router.url) }
  );

  isHome = () => this.pathname() === '/';

  constructor() {
    effect(onCleanup => {
      if (!this.isBrowser || !this.isHome()) return;

      const sectionIds = navItems.filter(item => item.href.startsWith('#')).map(item => item.id);
      const elements = sectionIds
        .map(id => document.getElementById(id))
        .filter((el): el is HTMLElement => el !== null);

      if (elements.length === 0) return;

      const observer = new IntersectionObserver(
        entries => {
          const visible = entries
            .filter(e => e.isIntersecting)
            .sort((a, b) => b.intersectionRatio - a.intersectionRatio);

          if (visible.length > 0) {
            this.activeId.set(visible[0].target.id);
          }
        },
        {
          rootMargin: '-20% 0px -55% 0px',
          threshold: [0, 0.1, 0.25, 0.5, 0.75, 1],
        }
      );

      elements.forEach(el => observer.observe(el));
      onCleanup(() => observer.disconnect());
    });
  }

  @HostListener('window:resize')
  onResize(): void {
    if (this.isBrowser && window.innerWidth >= 1024) this.menuOpen.set(false);
  }

  handleAnchorNav(href: string, id: string): void {
    this.activeId.set(id);
    this.menuOpen.set(false);
    if (!this.isBrowser) return;
    const target = document.querySelector(href);
    if (!target) return;
    const top = target.getBoundingClientRect().top + window.scrollY - 72;
    window.scrollTo({ top, behavior: 'smooth' });
  }

  toggleMenu(): void {
    this.menuOpen.set(!this.menuOpen());
  }

  isPageLink(item: NavItem): boolean {
    return item.href.startsWith('/');
  }

  isItemActive(item: NavItem): boolean {
    if (this.isPageLink(item)) {
      return this.pathname() === item.href || this.pathname().startsWith(`${item.href}/`);
    }
    return this.isHome() && this.activeId() === item.id;
  }

  navClass(item: NavItem, base = ''): string {
    const state = this.isItemActive(item)
      ? 'text-terminal-text'
      : 'text-terminal-dim hover:text-terminal-text';
    return `${base} transition-colors ${state}`;
  }

  offHomeAnchorHref(item: NavItem): string {
    return `/${item.href}`;
  }
}

<ng-template #navItemTpl let-item let-base="base">
  @if (isPageLink(item)) {
    <a
      [routerLink]="item.href"
      (click)="menuOpen.set(false)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'page' : null"
      >{{ item.label }}</a
    >
  } @else if (!isHome()) {
    <a
      [href]="offHomeAnchorHref(item)"
      (click)="menuOpen.set(false)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'page' : null"
      >{{ item.label }}</a
    >
  } @else {
    <button
      (click)="handleAnchorNav(item.href, item.id)"
      [class]="navClass(item, base)"
      [attr.aria-current]="isItemActive(item) ? 'true' : null"
    >
      {{ item.label }}
    </button>
  }
</ng-template>

<header class="sticky top-0 z-50 border-b border-term-dim bg-[rgba(6,11,22,0.85)] backdrop-blur-md font-mono text-[13px]">
  <div class="flex justify-between items-center gap-4 px-5 sm:px-6 md:px-14 py-[18px] max-w-content mx-auto">
    @if (isHome()) {
      <button
        (click)="handleAnchorNav('#home', 'home')"
        class="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
      >
        ~/yuko-pangestu
      </button>
    } @else {
      <a
        routerLink="/"
        class="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
      >
        ~/yuko-pangestu
      </a>
    }

    <!-- Desktop nav — lg+ so tablet doesn't crush 6 links + CTA -->
    <nav class="hidden lg:flex items-center gap-6 xl:gap-[30px]" aria-label="Primary">
      @for (item of navItems; track item.href) {
        <ng-container [ngTemplateOutlet]="navItemTpl" [ngTemplateOutletContext]="{ $implicit: item, base: '' }" />
      }
    </nav>

    <div class="flex items-center gap-3 sm:gap-4 shrink-0">
      <a
        href="mailto:yuko.pangestu@gmail.com"
        class="hidden lg:inline-block border border-terminal-primary text-terminal-blue px-[18px] py-2 rounded hover:bg-terminal-primary hover:text-white transition-colors"
      >
        hire --me
      </a>
      <button
        class="lg:hidden text-terminal-dim p-1 hover:text-terminal-text"
        (click)="toggleMenu()"
        aria-label="Toggle menu"
        [attr.aria-expanded]="menuOpen()"
      >
        <span class="font-mono text-sm">{{ menuOpen() ? 'close' : 'menu' }}</span>
      </button>
    </div>
  </div>

  @if (menuOpen()) {
    <div id="mobile-menu" class="lg:hidden flex flex-col px-5 sm:px-6 pb-6 gap-1 border-t border-term-dim">
      @for (item of navItems; track item.href) {
        <ng-container
          [ngTemplateOutlet]="navItemTpl"
          [ngTemplateOutletContext]="{ $implicit: item, base: 'text-left py-3 border-b border-term-dim last:border-0' }"
        />
      }
      <a
        href="mailto:yuko.pangestu@gmail.com"
        class="border border-terminal-primary text-terminal-blue px-[18px] py-3 rounded text-center mt-3 hover:bg-terminal-primary hover:text-white transition-colors"
      >
        hire --me
      </a>
    </div>
  }
</header>

// src/components/Header.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const navItems = [
  { label: './home', href: '#home', id: 'home' },
  { label: './skills', href: '#skills', id: 'skills' },
  { label: './portfolio', href: '/portfolio', id: 'portfolio' },
  { label: './experience', href: '#experience', id: 'experience' },
  { label: './blog', href: '/blog', id: 'blog' },
  { label: './contact', href: '#contact', id: 'contact' },
];

export default function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeId, setActiveId] = useState('home');
  const pathname = usePathname();
  const isHome = pathname === '/';

  useEffect(() => {
    if (!isHome) return;

    const sectionIds = navItems.filter(item => item.href.startsWith('#')).map(item => item.id);
    const elements = sectionIds
      .map(id => document.getElementById(id))
      .filter((el): el is HTMLElement => el !== null);

    if (elements.length === 0) return;

    const observer = new IntersectionObserver(
      entries => {
        const visible = entries
          .filter(e => e.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio);

        if (visible.length > 0) {
          setActiveId(visible[0].target.id);
        }
      },
      {
        rootMargin: '-20% 0px -55% 0px',
        threshold: [0, 0.1, 0.25, 0.5, 0.75, 1],
      }
    );

    elements.forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, [isHome]);

  // Close mobile menu on resize to desktop
  useEffect(() => {
    const onResize = () => {
      if (window.innerWidth >= 1024) setMenuOpen(false);
    };
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  const handleAnchorNav = (href: string, id: string) => {
    setActiveId(id);
    setMenuOpen(false);
    const target = document.querySelector(href);
    if (!target) return;
    const top = (target as HTMLElement).getBoundingClientRect().top + window.scrollY - 72;
    window.scrollTo({ top, behavior: 'smooth' });
  };

  const isItemActive = (item: (typeof navItems)[number]) => {
    if (item.href.startsWith('/')) return pathname === item.href || pathname.startsWith(`${item.href}/`);
    return isHome && activeId === item.id;
  };

  const navClass = (item: (typeof navItems)[number], base = '') =>
    `${base} transition-colors ${
      isItemActive(item)
        ? 'text-terminal-text'
        : 'text-terminal-dim hover:text-terminal-text'
    }`;

  const renderNavItem = (item: (typeof navItems)[number], base: string) => {
    const isPageLink = item.href.startsWith('/');

    if (isPageLink || !isHome) {
      const href = isPageLink ? item.href : `/${item.href}`;
      return (
        <Link
          key={item.href}
          href={href}
          onClick={() => setMenuOpen(false)}
          className={navClass(item, base)}
          aria-current={isItemActive(item) ? 'page' : undefined}
        >
          {item.label}
        </Link>
      );
    }

    return (
      <button
        key={item.href}
        onClick={() => handleAnchorNav(item.href, item.id)}
        className={navClass(item, base)}
        aria-current={isItemActive(item) ? 'true' : undefined}
      >
        {item.label}
      </button>
    );
  };

  return (
    <header className="sticky top-0 z-50 border-b border-term-dim bg-[rgba(6,11,22,0.85)] backdrop-blur-md font-mono text-[13px]">
      <div className="flex justify-between items-center gap-4 px-5 sm:px-6 md:px-14 py-[18px] max-w-content mx-auto">
        {isHome ? (
          <button
            onClick={() => handleAnchorNav('#home', 'home')}
            className="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
          >
            ~/yuko-pangestu
          </button>
        ) : (
          <Link
            href="/"
            className="text-terminal-blue font-bold hover:text-terminal-blue-bright transition-colors shrink-0 text-[12px] sm:text-[13px]"
          >
            ~/yuko-pangestu
          </Link>
        )}

        {/* Desktop nav — lg+ so tablet doesn't crush 6 links + CTA */}
        <nav className="hidden lg:flex items-center gap-6 xl:gap-[30px]" aria-label="Primary">
          {navItems.map(item => renderNavItem(item, ''))}
        </nav>

        <div className="flex items-center gap-3 sm:gap-4 shrink-0">
          <a
            href="mailto:yuko.pangestu@gmail.com"
            className="hidden lg:inline-block border border-terminal-primary text-terminal-blue px-[18px] py-2 rounded hover:bg-terminal-primary hover:text-white transition-colors"
          >
            hire --me
          </a>
          <button
            className="lg:hidden text-terminal-dim p-1 hover:text-terminal-text"
            onClick={() => setMenuOpen(o => !o)}
            aria-label="Toggle menu"
            aria-expanded={menuOpen}
          >
            <span className="font-mono text-sm">{menuOpen ? 'close' : 'menu'}</span>
          </button>
        </div>
      </div>

      {menuOpen && (
        <div
          id="mobile-menu"
          className="lg:hidden flex flex-col px-5 sm:px-6 pb-6 gap-1 border-t border-term-dim"
        >
          {navItems.map(item => renderNavItem(item, 'text-left py-3 border-b border-term-dim last:border-0'))}
          <a
            href="mailto:yuko.pangestu@gmail.com"
            className="border border-terminal-primary text-terminal-blue px-[18px] py-3 rounded text-center mt-3 hover:bg-terminal-primary hover:text-white transition-colors"
          >
            hire --me
          </a>
        </div>
      )}
    </header>
  );
}
